# Staging Configuration

server:
  port: 8080
  
spring:
  application:
    name: demo-application
  
  datasource:
    url: jdbc:mysql://staging-db-server:3306/staging_db
    username: staging_user
    password: ${STAGING_DB_PASSWORD}
    
logging:
  level:
    root: DEBUG
    org.springframework: INFO
